"""gabungan

Revision ID: b5bf7c456e88
Revises: 
Create Date: 2022-06-20 14:25:46.212356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5bf7c456e88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=99), nullable=False),
    sa.Column('nama', sa.String(length=99), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_id'), 'admin', ['id'], unique=False)
    op.create_table('auth',
    sa.Column('id_auth', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status_auth', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=99), nullable=False),
    sa.Column('password', sa.String(length=99), nullable=False),
    sa.Column('flag', sa.String(length=2), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id_auth')
    )
    op.create_table('buku',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kodebuku', sa.String(length=30), nullable=False),
    sa.Column('judul', sa.String(length=99), nullable=False),
    sa.Column('genre', sa.String(length=30), nullable=False),
    sa.Column('lokasi', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=30), nullable=True),
    sa.Column('flag', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buku_id'), 'buku', ['id'], unique=False)
    op.create_index(op.f('ix_buku_kodebuku'), 'buku', ['kodebuku'], unique=True)
    op.create_table('member',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idmember', sa.String(length=30), nullable=False),
    sa.Column('nik', sa.String(length=16), nullable=False),
    sa.Column('nama', sa.String(length=99), nullable=False),
    sa.Column('jenis_kelamin', sa.String(length=10), nullable=False),
    sa.Column('alamat', sa.String(length=99), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=30), nullable=True),
    sa.Column('flag', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_id'), 'member', ['id'], unique=False)
    op.create_index(op.f('ix_member_idmember'), 'member', ['idmember'], unique=True)
    op.create_table('admins',
    sa.Column('id_admin', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_auth', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=99), nullable=False),
    sa.Column('password', sa.String(length=99), nullable=False),
    sa.Column('nama_admin', sa.String(length=80), nullable=False),
    sa.Column('jabatan', sa.String(length=80), nullable=False),
    sa.Column('flag', sa.String(length=2), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_auth'], ['auth.id_auth'], ),
    sa.PrimaryKeyConstraint('id_admin')
    )
    op.create_table('dokter',
    sa.Column('id_dokter', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_auth', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=99), nullable=False),
    sa.Column('password', sa.String(length=99), nullable=False),
    sa.Column('nama_dokter', sa.String(length=80), nullable=False),
    sa.Column('hari_kerja', sa.String(length=80), nullable=False),
    sa.Column('jam_kerja', sa.String(length=80), nullable=False),
    sa.Column('kuota', sa.Integer(), nullable=False),
    sa.Column('flag', sa.String(length=2), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_auth'], ['auth.id_auth'], ),
    sa.PrimaryKeyConstraint('id_dokter')
    )
    op.create_table('pasien',
    sa.Column('no_pasien', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_auth', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=99), nullable=False),
    sa.Column('password', sa.String(length=99), nullable=False),
    sa.Column('nama_pasien', sa.String(length=80), nullable=False),
    sa.Column('alamat_pasien', sa.String(length=80), nullable=False),
    sa.Column('status_diperiksa', sa.String(length=2), nullable=False),
    sa.Column('flag', sa.String(length=2), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_auth'], ['auth.id_auth'], ),
    sa.PrimaryKeyConstraint('no_pasien')
    )
    op.create_table('transaksi',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idmember', sa.String(length=6), nullable=False),
    sa.Column('kodebuku', sa.String(length=6), nullable=False),
    sa.Column('tgl_pinjam', sa.Date(), nullable=False),
    sa.Column('tgl_kembali', sa.Date(), nullable=False),
    sa.Column('idadmin', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.String(length=30), nullable=True),
    sa.Column('flag', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['idadmin'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['idmember'], ['member.idmember'], ),
    sa.ForeignKeyConstraint(['kodebuku'], ['buku.kodebuku'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaksi_id'), 'transaksi', ['id'], unique=False)
    op.create_table('admin_history',
    sa.Column('id_admin_history', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_admin', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=99), nullable=False),
    sa.Column('nama_admin', sa.String(length=80), nullable=False),
    sa.Column('jabatan', sa.String(length=80), nullable=False),
    sa.Column('flag', sa.String(length=2), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_admin'], ['admins.id_admin'], ),
    sa.PrimaryKeyConstraint('id_admin_history')
    )
    op.create_table('dokter_history',
    sa.Column('no_dokter_history', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_dokter', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=99), nullable=False),
    sa.Column('nama_dokter', sa.String(length=80), nullable=False),
    sa.Column('hari_kerja', sa.String(length=80), nullable=False),
    sa.Column('jam_kerja', sa.String(length=80), nullable=False),
    sa.Column('kuota', sa.Integer(), nullable=False),
    sa.Column('flag', sa.String(length=2), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_dokter'], ['dokter.id_dokter'], ),
    sa.PrimaryKeyConstraint('no_dokter_history')
    )
    op.create_table('pasien_history',
    sa.Column('no_pasien_history', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('no_pasien', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=99), nullable=False),
    sa.Column('nama_pasien', sa.String(length=80), nullable=False),
    sa.Column('alamat_pasien', sa.String(length=80), nullable=False),
    sa.Column('flag', sa.String(length=2), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['no_pasien'], ['pasien.no_pasien'], ),
    sa.PrimaryKeyConstraint('no_pasien_history')
    )
    op.create_table('trans',
    sa.Column('id_trans', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_dokter', sa.Integer(), nullable=True),
    sa.Column('no_pasien', sa.Integer(), nullable=True),
    sa.Column('status_bayar', sa.String(length=2), nullable=False),
    sa.Column('status_checking_dokter', sa.String(length=2), nullable=False),
    sa.Column('resep_dokter', sa.String(length=99), nullable=False),
    sa.Column('harga_bayar', sa.Integer(), nullable=False),
    sa.Column('keluhan', sa.String(length=99), nullable=False),
    sa.Column('flag', sa.String(length=2), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_dokter'], ['dokter.id_dokter'], ),
    sa.ForeignKeyConstraint(['no_pasien'], ['pasien.no_pasien'], ),
    sa.PrimaryKeyConstraint('id_trans')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trans')
    op.drop_table('pasien_history')
    op.drop_table('dokter_history')
    op.drop_table('admin_history')
    op.drop_index(op.f('ix_transaksi_id'), table_name='transaksi')
    op.drop_table('transaksi')
    op.drop_table('pasien')
    op.drop_table('dokter')
    op.drop_table('admins')
    op.drop_index(op.f('ix_member_idmember'), table_name='member')
    op.drop_index(op.f('ix_member_id'), table_name='member')
    op.drop_table('member')
    op.drop_index(op.f('ix_buku_kodebuku'), table_name='buku')
    op.drop_index(op.f('ix_buku_id'), table_name='buku')
    op.drop_table('buku')
    op.drop_table('auth')
    op.drop_index(op.f('ix_admin_id'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
